### ISSUE TITLE
A basic example to get the gist of the package

### ISSUE THREAD

**Issue by LRydin** [arthur-e/MOD16#5]
Hey @arthur-e, I'm interested in doing some rather elementary estimation of soil evaporation for a South African crop. I think your package would be one good way to get started, but I am missing the element of how-to-get-started. I believe I have to start with [`evaporation_soil`](https://arthur-e.github.io/MOD16/#mod16.MOD16.evaporation_soil), but this function alone takes 6 mandatory parameters (+3 optional).

Is there a way to add a minimal-working example to get started with a calculation of this? E.g., I can see that `evaporation_soil` takes 6 arguments (pressure, temp, ...). I suspect I can obtain, e.g., `vpd` via the defined [`vdp` function](https://arthur-e.github.io/MOD16/#vpd), but for that I need `qv10m`.

Any chance there is a tutorial or a "how-to-get-started" you can point me to?

**Comment by arthur-e** [comment]
Hi @LRydin, this is a very reasonable request and something I want to include the package documentation. It will take me a few more days but I will publish a Jupyter Notebook, soon, that should help you get started. In the meantime, here are some tips.

The first thing to do would be to create a model instance with known model parameters. For example, if you want to use the same parameters as MOD16 Collection 6.1 (most recent version before Collection 7, which is currently being processed), you would need to load the Biome Properties Lookup Table (BPLUT) for that version.

```python
import os
import mod16
from mod16.utils import restore_bplut

# Get the location of the MOD16 repo on your file system
repo_dir = os.path.dirname(mod16.__file__)

# Get the path to the BPLUT
bplut_path = repo_dir + '/data/MOD16_BPLUT_C5.1_05deg_MCD43B_Albedo_MERRA_GMAO.csv'

# Read in the file as a dictionary of parameters for each Plant Functional Type (PFT)
params_dict = restore_bplut(bplut_path)
```

What is `params_dict`? It's a dictionary of NumPy arrays, where the parameters are ordered by PFT. Croplands are PFT 12 (see [the MOD16 User Guide](https://lpdaac.usgs.gov/documents/931/MOD16_User_Guide_V61.pdf), Table 3.1), so those parameters could be extracted like this:

```python
params = dict([(key, params_dict[key][12]) for key in params_dict.keys()])
```
```
>>> params
{'tmin_close': -8.0,
 'tmin_open': 12.02,
 'vpd_open': 650.0,
 'vpd_close': 4500.0,
 'gl_sh': 0.02,
 'gl_wv': 0.02,
 'g_cuticular': 1e-05,
 'csl': 0.0055,
 'rbl_min': 60.0,
 'rbl_max': 95.0,
 'beta': nan}
```

**These parameters can be found in Table 3.2 of the User Guide, so you could also just construct a `list` manually using that table.**

One confusing bit, we need to manually set the value of `beta` (can be found in the User Guide).

```python
params['beta'] = 250
```

Now we're ready to create a model instance. Note that the model functions are vectorized so you can calculate rates of soil evaporation for a single point, just by providing atomic values:

```python
model = MOD16(params)

# Soil evaporation near sea-level, at 20 deg C, VPD of 1000 Pa, fPAR of 0.5...
model.evaporation_soil(101e3, 293.15, 1000, 0.5, 100)
```

Finally, if you want to start working with representative (cropland) data, you can download the file `VNP16_MOD16_tower_site_latent_heat_and_drivers_v7.h5` from [our published archive](https://zenodo.org/records/13988806). This HDF5 file should be fairly self-documenting, with meteorological driver data under the "GEOS" or "MERRA-2" groups (depending on which source you want to use) and canopy fPAR and LAI data under the "MODIS" or "VIIRS" groups (depending on which you want to use.

**Comment by LRydin** [comment]
Dear @arthur-e, this is wonderful and a very nice way to get started, thank you! I'll dive into this soon enough. Wonderful.

**Comment by arthur-e** [comment]
@LRydin I forgot that the `notebooks` folder has been available for awhile. I just updated this example notebook, which is pretty comprehensive:

[`MOD16_Forward_Run_example.ipynb`](https://github.com/arthur-e/MOD16/blob/master/notebooks/MOD16_Forward_Run_example.ipynb)

If there are any issues or clarifications needed, please let me know. I would also welcome any Pull Requests.

**Comment by LRydin** [comment]
Perfect, thank you very much!
